### PR TITLE
Update package for PHP 8

### PR DESCRIPTION
**Pull request by jmsmith84**

### CODE REVIEW

**Comment by michael-o** [comment]
Why wasn't this merged?

**Comment by philip** [comment]
@michael-o I'm guessing because the patch removes PHP 7 support.

**Comment by jmsmith84** [comment]
@michael-o Sorry for the late reply, I closed it because I did a bit more cleanup than was necessary just to get it working for PHP8 so I figured it would not be welcomed. 
For example I removed one of the engines that was not passing its own unit tests seemingly due to incompatibility with recent versions of the linux shell command it was relying on.

If this repo is still being maintained I could make a new PR that only contains the required change (I believe there was only one).

**Comment by michael-o** [comment]
The big question  is for me as WebSVN maintainer: Does it make a difference in using this lib compared to `diff(1)`?

**Pull request closed without merging**
